name: LPG Web CI

on:
  push:
    tags: [ "v*" ]
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-lgp-web:
    name: Build LPG Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "8"
          run_install: false

      - name: Get pnpm store directory
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Set up pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies and build
        env:
          VITE_WEBSITE_TITLE: ${{ secrets.VITE_WEBSITE_TITLE }}
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpg-web-artifact-${{ runner.os }}
          path: dist

  docker-build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    needs:
      - build-lgp-web
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: docker_buildx

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/lpg-web
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lpg-web-artifact-${{ runner.os }}
          path: dist

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/386
          push: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max